#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=69436147995
BundleId=com.xtudio16.triviacatracha
ClientId=69436147995-4t3u2vanctc2pc4r3g1simahh3iib0qq.apps.googleusercontent.com

*/

#define kAppID "69436147995"
#define kBundleID "com.xtudio16.triviacatracha"
#define kClientID "69436147995-4t3u2vanctc2pc4r3g1simahh3iib0qq.apps.googleusercontent.com"

#endif


